# This code updates the YouTube Cards info e.g. Views


# This file is no longer in use but can be useful for someone else
# what it does is that when you put your YT vids on github well this script
# updates the view count on the video and other factors

name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Allow the job to commit to the repository
    permissions:
      contents: write
    # Run the GitHub Readme YouTube Cards action
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCzzGpscAqcUi10T4u-sWyyg
