name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch: 


jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          comment_tag_name: YOUTUBE-CARDS
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCzzGpscAqcUi10T4u-sWyyg"
          show_duration: true
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
